# Generated by Django 4.2.2 on 2025-04-11 10:18
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0003_remove_order_city_remove_order_flat_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Adress",
            new_name="Address",
        ),
        migrations.RenameField(
            model_name="address",
            old_name="adress",
            new_name="address",
        ),
    ]
