# Generated by Django 4.2.2 on 2025-04-11 10:30
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_rename_adress_address_rename_adress_address_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="order",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="address", to="orders.order"),
        ),
    ]
