# Generated by Django 4.2.2 on 2025-05-19 11:17
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0007_alter_orderitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name="addresses", to=settings.AUTH_USER_MODEL),
        ),
    ]
