# Generated by Django 4.2.2 on 2025-03-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_categories_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/imgs', verbose_name='Фото'),
        ),
    ]
