# Generated by Django 4.2.2 on 2024-12-29 11:06
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "Пользоваетль", "verbose_name_plural": "Пользователи"},
        ),
    ]
