# Generated by Django 4.2.2 on 2024-12-29 11:06
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attribute",
            options={"verbose_name": "Атрибут", "verbose_name_plural": "Атрибуты"},
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["name"], "verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AlterModelOptions(
            name="itemattribute",
            options={"verbose_name": "Атрибут товара", "verbose_name_plural": "Атрибуты товаров"},
        ),
        migrations.AlterModelOptions(
            name="itemimage",
            options={"verbose_name": "Фото товара", "verbose_name_plural": "Фотографии товаров"},
        ),
        migrations.AlterModelOptions(
            name="recommenditem",
            options={"verbose_name": "Рекомендуемый товар", "verbose_name_plural": "Рекомендуемые товары"},
        ),
        migrations.AlterField(
            model_name="item",
            name="available",
            field=models.BooleanField(blank=True, null=True, verbose_name="Досутпен ли"),
        ),
        migrations.AlterField(
            model_name="item",
            name="discount_percent",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name="Скидка"),
        ),
    ]
