# Generated by Django 4.2.2 on 2024-12-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_attribute_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Досутпен ли'),
        ),
    ]
