name: CI/CD PipeLinee


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build-backend:
    name: Build Django Backend
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.7

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run tests
        env:
            DJANGO_SECRET_KEY: ${{ secrets.SECRET_KEY }}
            DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
            CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }}
        run: |
          cd backend
          pytest

  build-frontend:
    name: Build Vue.js Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          cd frontend
          yarn install

      - name: Run tests
        run: |
          cd frontend
          yarn test

      - name: Build for production
        run: |
          cd frontend
          yarn build

  docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push backend Docker image
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/django-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/django-backend:latest

      - name: Build and push frontend Docker image
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/vue-frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/vue-frontend:latest

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Deploy
        run: |
          ssh user@yourserver.com <<EOF
          docker pull ${{ secrets.DOCKER_USERNAME }}/django-backend:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/vue-frontend:latest
          docker-compose -f /path/to/docker-compose.yml up -d --no-deps backend frontend
          EOF
